nama = input("Masukkan nama : ")
umur = int(input("Masukkan umur : "))
tinggi = float(input("Masukkan tinggi : "))
text = "Nama saya {}, umur saya {} tahun dan tinggi saya {} cm.".format(nama,umur,tinggi)
print(text)